### PR TITLE
Add caselists to cBio importer

### PR DESCRIPTION
**Pull request by mokolodi1**
All the changes made here are either in Robert's personal run files or in `tools/cbioportal`.

No app code has changed, so no need to bump the docker versions.

### CODE REVIEW

**Comment by rbaertsch** [comment]
The binary .pyc file should probably be removed.   I'm not sure why the version number on collection hooks keeps getting bumped. Either way is find for me.

**Comment by mokolodi1** [comment]
Could you remove it and push?

**Comment by rbaertsch** [comment]
tools/cbioportal/importer/cbioportal_common.pyc removed

**Review by e-t-k — APPROVED** [review]
I've reverted the collection-hooks file for consistency -- otherwise, lgtm.

**Comment by e-t-k** [comment]
Once travis completes again I'll check out these changes on prod.

**Comment by e-t-k** [comment]
Commit ffdabfd is now live on prod. Dockers were *not* restarted as the only changes are in docs & the tools folder, which relies on the git checkout rather than docker. Cheers.

**Pull request merged**
